version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
      timezone: "America/Chicago"
    reviewers:
      - "spencerjanssen"
